services:
  api:
    build: 
      context: .
      dockerfile: dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    container_name: raizes_do_nordeste
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mock:
    build: .
    command: uvicorn api_mock:app --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"

#https://docs.docker.com/engine/storage/volumes/#use-a-volume-with-docker-compose

  mysql:
    image: mysql:lts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 20
    container_name: db_mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    external: false
    name: "banco_raizes_do_nordeste"