FROM python

#Cria a pasta inicial e dá permissão ao usuário de alterar
RUN mkdir -p /home/python/server && chown -R python:python /home/python/server

#Configura a pasta de trabalho padrão (não precisa mexer em outras)
WORKDIR /home/python/server

#Cria pastas dos pacotes-padrão
RUN mkdir -p python_packages && chown -R python:python python_packages

#Traz os arquivos de dependência para dentro do arquivo - para criar dependências a partir do container
COPY --chown=python:python Database Models Routes Schemas dependencies.py main.py requirements.txt ./

USER python

RUN python3 -m venv .venv

RUN source .venv/bin/activate

RUN pip install -r requirements.txt

EXPOSE ${PORT}

CMD ['uvicorn', 'main:app', '--reload']
