"""Adição de idPagamento

Revision ID: 034c15477239
Revises: f4b86233bd92
Create Date: 2026-06-19 13:19:53.459984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034c15477239'
down_revision: Union[str, Sequence[str], None] = 'f4b86233bd92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('IdPagamento', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'IdPagamento')
    # ### end Alembic commands ###
