"""adição de 'atualizar campo' nas ações de log

Revision ID: 1af632880647
Revises: dfcef4f9a4df
Create Date: 2026-06-24 09:11:53.887450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af632880647'
down_revision: Union[str, Sequence[str], None] = 'dfcef4f9a4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
