"""ajustes de enum log

Revision ID: 24e099711d45
Revises: c92108a71f1d
Create Date: 2026-06-20 18:25:13.585077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '24e099711d45'
down_revision: Union[str, Sequence[str], None] = 'c92108a71f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'Tabela',
               existing_type=mysql.ENUM('pedidos', 'pedidoItens', 'movimentos', 'movimentoItens', 'usuarios', 'clientes', 'variacoes', 'produtos', 'ingredientes', 'filiais', 'estoqueItens', 'estoques', 'campanhasPromos', 'variacoesFiliais', 'usuariosFiliais', 'promosFiliais', 'itensReceitas'),
               type_=sa.Enum('pedidos', 'pedidoItens', 'movimentos', 'movimentoItens', 'usuarios', 'clientes', 'variacoes', 'produtos', 'ingredientes', 'filiais', 'estoqueItens', 'estoques', 'campanhaPromos', 'variacoesFiliais', 'usuariosFiliais', 'filiaisPromos', 'receitasItens', name='tabelas'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'Tabela',
               existing_type=sa.Enum('pedidos', 'pedidoItens', 'movimentos', 'movimentoItens', 'usuarios', 'clientes', 'variacoes', 'produtos', 'ingredientes', 'filiais', 'estoqueItens', 'estoques', 'campanhaPromos', 'variacoesFiliais', 'usuariosFiliais', 'filiaisPromos', 'receitasItens', name='tabelas'),
               type_=mysql.ENUM('pedidos', 'pedidoItens', 'movimentos', 'movimentoItens', 'usuarios', 'clientes', 'variacoes', 'produtos', 'ingredientes', 'filiais', 'estoqueItens', 'estoques', 'campanhasPromos', 'variacoesFiliais', 'usuariosFiliais', 'promosFiliais', 'itensReceitas'),
               existing_nullable=True)
    # ### end Alembic commands ###
