"""Migracao 3

Revision ID: 300081de09b2
Revises: 0052a9c13c7b
Create Date: 2026-06-09 00:35:01.118684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300081de09b2'
down_revision: Union[str, Sequence[str], None] = '0052a9c13c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nome', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=50), nullable=False),
    sa.Column('CPF', sa.String(length=50), nullable=False),
    sa.Column('Escaneamento facial', sa.String(length=200), nullable=True),
    sa.Column('Senha', sa.String(length=200), nullable=False),
    sa.Column('Endereço', sa.String(length=80), nullable=True),
    sa.Column('Fidelidade', sa.Integer(), nullable=False),
    sa.Column('Nascimento', sa.Date(), nullable=False),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
