"""fix na filial

Revision ID: 39e30161fac2
Revises: 8c367069c4a6
Create Date: 2026-06-15 23:30:46.257320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e30161fac2'
down_revision: Union[str, Sequence[str], None] = '8c367069c4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variacoes', sa.Column('Produto', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'variacoes', 'produtos', ['Produto'], ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variacoes', type_='foreignkey')
    op.drop_column('variacoes', 'Produto')
    # ### end Alembic commands ###
