"""Adição de identificador de log

Revision ID: 4748b720e995
Revises: 24e099711d45
Create Date: 2026-06-22 15:17:48.212274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4748b720e995'
down_revision: Union[str, Sequence[str], None] = '24e099711d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('IdModificado', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'IdModificado')
    # ### end Alembic commands ###
