"""Expansão de campos Logs

Revision ID: 59a294014e17
Revises: 418fb094655f
Create Date: 2026-06-23 01:48:44.948678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59a294014e17'
down_revision: Union[str, Sequence[str], None] = '418fb094655f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'Campo',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('logs', 'ValorAnterior',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('logs', 'ValorNovo',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'ValorNovo',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('logs', 'ValorAnterior',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('logs', 'Campo',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
