"""Migracao 4

Revision ID: 607c301db3c1
Revises: 300081de09b2
Create Date: 2026-06-09 00:35:29.261730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '607c301db3c1'
down_revision: Union[str, Sequence[str], None] = '300081de09b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('Escaneamento_facial', sa.String(length=200), nullable=True))
    op.drop_column('clientes', 'Escaneamento facial')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('Escaneamento facial', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('clientes', 'Escaneamento_facial')
    # ### end Alembic commands ###
