"""StatusPagamento como enum

Revision ID: 742d607a3773
Revises: fcc0b579fdb6
Create Date: 2026-06-23 00:50:11.184404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '742d607a3773'
down_revision: Union[str, Sequence[str], None] = 'fcc0b579fdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'StatusPagamento',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.Enum('Aguardando Fechamento', 'Pendente', 'Cancelado', 'Estornado', 'Aprovado', name='statuspagamento'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'StatusPagamento',
               existing_type=sa.Enum('Aguardando Fechamento', 'Pendente', 'Cancelado', 'Estornado', 'Aprovado', name='statuspagamento'),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###
