"""Modelagem geral bruta

Revision ID: a77eb9439b2f
Revises: da1b32827b39
Create Date: 2026-06-15 15:22:22.500240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77eb9439b2f'
down_revision: Union[str, Sequence[str], None] = 'da1b32827b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filiais',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Cidade', sa.String(length=100), nullable=False),
    sa.Column('Estrutura', sa.Enum('Completa', 'Reduzida', name='estrutura'), nullable=False),
    sa.Column('Endereco', sa.String(length=100), nullable=False),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('ContaBanco', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('ingredientes',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nome', sa.String(length=80), nullable=False),
    sa.Column('Periodo', sa.Enum('Verão', 'Outono', 'Inverno', 'Primavera', name='periodoano'), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('logs',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Acao', sa.String(length=80), nullable=False),
    sa.Column('Tabela', sa.Enum('pedidos', 'pedidoItens', 'movimentos', 'movimentoItens', 'usuarios', 'clientes', 'variacoes', 'produtos', 'ingredientes', 'filiais', 'estoqueItens', 'estoques', 'campanhasPromos', 'variacoesFiliais', 'usuariosFiliais', 'promosFiliais', 'itensReceitas', name='tabelas'), nullable=True),
    sa.Column('Campo', sa.String(length=30), nullable=False),
    sa.Column('ValorAnterior', sa.String(length=80), nullable=False),
    sa.Column('ValorNovo', sa.String(length=80), nullable=False),
    sa.Column('TipoPessoa', sa.Enum('Usuario', 'Cliente', name='tipologin'), nullable=True),
    sa.Column('IdPessoa', sa.Integer(), nullable=False),
    sa.Column('DataHora', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('produtos',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nome', sa.String(length=80), nullable=False),
    sa.Column('Ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('variacoes',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nome', sa.String(length=80), nullable=False),
    sa.Column('PrecoUnitario', sa.Float(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('estoques',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Filial', sa.Integer(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Filial'], ['filiais.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('filiaisPromos',
    sa.Column('CampanhaPromo', sa.Integer(), nullable=False),
    sa.Column('Filial', sa.Integer(), nullable=False),
    sa.Column('Ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['CampanhaPromo'], ['campanhaPromos.ID'], ),
    sa.ForeignKeyConstraint(['Filial'], ['filiais.ID'], ),
    sa.PrimaryKeyConstraint('CampanhaPromo', 'Filial')
    )
    op.create_table('movimentos',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('DataHora', sa.DateTime(), nullable=False),
    sa.Column('Status', sa.Enum('Aguardando Entrega', 'Em Revisão', 'Inconsistente', 'Cancelado', 'Validado', name='statusmov'), nullable=False),
    sa.Column('Filial', sa.Integer(), nullable=True),
    sa.Column('Tipo', sa.Enum('Entrada', 'Saída', name='tipomov'), nullable=False),
    sa.Column('Validade', sa.DateTime(), nullable=False),
    sa.Column('ChaveNota', sa.String(length=44), nullable=True),
    sa.ForeignKeyConstraint(['Filial'], ['filiais.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('pedidos',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Filial', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Enum('Aberto', 'Fechado', 'Preparação', 'Aguardando Coleta', 'Em Trânsito', 'Cancelado', 'Recebido', 'Estornado', name='statuscode'), nullable=False),
    sa.Column('Tipo', sa.Enum('Entrega', 'Mesa', 'Retirada', 'Balcão', name='tiposped'), nullable=False),
    sa.Column('Canal', sa.Enum('App', 'Totem', 'Retirada', 'Pickup', 'Web', name='canalpedido'), nullable=False),
    sa.Column('Criador', sa.Enum('Usuario', 'Cliente', name='tipologin'), nullable=False),
    sa.Column('IdCriador', sa.Integer(), nullable=False),
    sa.Column('Cliente', sa.Integer(), nullable=True),
    sa.Column('Modificador', sa.Enum('Usuario', 'Cliente', name='tipologin'), nullable=False),
    sa.Column('IdModificador', sa.Integer(), nullable=False),
    sa.Column('DataHora', sa.DateTime(), nullable=False),
    sa.Column('Mesa', sa.Integer(), nullable=True),
    sa.Column('Chamada', sa.Integer(), nullable=True),
    sa.Column('Endereco', sa.String(length=80), nullable=True),
    sa.Column('SomaItens', sa.Float(), nullable=False),
    sa.Column('Frete', sa.Float(), nullable=False),
    sa.Column('Total', sa.Float(), nullable=False),
    sa.Column('FormaPagamento', sa.Enum('Mock', 'Crédito', 'Débito', name='formapagamento'), nullable=False),
    sa.Column('PontosFidelidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Cliente'], ['clientes.ID'], ),
    sa.ForeignKeyConstraint(['Filial'], ['filiais.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('receitasItens',
    sa.Column('Variacao', sa.Integer(), nullable=False),
    sa.Column('Ingredientes', sa.Integer(), nullable=False),
    sa.Column('Quantidade', sa.Float(), nullable=False),
    sa.Column('UnidadeMedida', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['Ingredientes'], ['ingredientes.ID'], ),
    sa.ForeignKeyConstraint(['Variacao'], ['variacoes.ID'], ),
    sa.PrimaryKeyConstraint('Variacao', 'Ingredientes')
    )
    op.create_table('usuariosFiliais',
    sa.Column('IdUsuario', sa.Integer(), nullable=False),
    sa.Column('IdFilial', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IdFilial'], ['filiais.ID'], ),
    sa.ForeignKeyConstraint(['IdUsuario'], ['usuarios.ID'], ),
    sa.PrimaryKeyConstraint('IdUsuario', 'IdFilial')
    )
    op.create_table('variacoesFiliais',
    sa.Column('Variacao', sa.Integer(), nullable=False),
    sa.Column('Filial', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Filial'], ['filiais.ID'], ),
    sa.ForeignKeyConstraint(['Variacao'], ['variacoes.ID'], ),
    sa.PrimaryKeyConstraint('Variacao', 'Filial')
    )
    op.create_table('estoqueItens',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Estoque', sa.Integer(), nullable=True),
    sa.Column('Ingrediente', sa.Integer(), nullable=True),
    sa.Column('Quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Estoque'], ['estoques.ID'], ),
    sa.ForeignKeyConstraint(['Ingrediente'], ['ingredientes.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('movimentoItens',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Ingrediente', sa.Integer(), nullable=True),
    sa.Column('Movimento', sa.Integer(), nullable=True),
    sa.Column('Quantidade', sa.Integer(), nullable=False),
    sa.Column('Validade', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Ingrediente'], ['ingredientes.ID'], ),
    sa.ForeignKeyConstraint(['Movimento'], ['movimentos.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('pedidoItens',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Pedido', sa.Integer(), nullable=True),
    sa.Column('Variacao', sa.Integer(), nullable=True),
    sa.Column('Quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Pedido'], ['pedidos.ID'], ),
    sa.ForeignKeyConstraint(['Variacao'], ['variacoes.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidoItens')
    op.drop_table('movimentoItens')
    op.drop_table('estoqueItens')
    op.drop_table('variacoesFiliais')
    op.drop_table('usuariosFiliais')
    op.drop_table('receitasItens')
    op.drop_table('pedidos')
    op.drop_table('movimentos')
    op.drop_table('filiaisPromos')
    op.drop_table('estoques')
    op.drop_table('variacoes')
    op.drop_table('produtos')
    op.drop_table('logs')
    op.drop_table('ingredientes')
    op.drop_table('filiais')
    # ### end Alembic commands ###
