"""Adição de status de pedido para auditoria de erros

Revision ID: ab585915e686
Revises: 034c15477239
Create Date: 2026-06-20 00:16:17.049207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab585915e686'
down_revision: Union[str, Sequence[str], None] = '034c15477239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('StatusPagamento', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'StatusPagamento')
    # ### end Alembic commands ###
