"""cargo como enum

Revision ID: da1b32827b39
Revises: 607c301db3c1
Create Date: 2026-06-12 14:50:49.115744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da1b32827b39'
down_revision: Union[str, Sequence[str], None] = '607c301db3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'Cargo',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('Não Classificado', 'Gerente', 'Atendente', 'Cozinheiro', 'TI', 'CEO', name='cargo'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'Cargo',
               existing_type=sa.Enum('Não Classificado', 'Gerente', 'Atendente', 'Cozinheiro', 'TI', 'CEO', name='cargo'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
