"""ação dos logs agora como enum para facilitar filtro

Revision ID: dfcef4f9a4df
Revises: e27a360c6ec4
Create Date: 2026-06-23 22:51:31.456852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dfcef4f9a4df'
down_revision: Union[str, Sequence[str], None] = 'e27a360c6ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'Acao',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.Enum('criar', 'ativar', 'desativar', 'editar', 'excluir', 'alterar status', name='acoes'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'Acao',
               existing_type=sa.Enum('criar', 'ativar', 'desativar', 'editar', 'excluir', 'alterar status', name='acoes'),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
