"""adição de campo ativo nos ingredientes

Revision ID: e27a360c6ec4
Revises: fe39a3dff618
Create Date: 2026-06-23 13:39:50.843633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27a360c6ec4'
down_revision: Union[str, Sequence[str], None] = 'fe39a3dff618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredientes', sa.Column('Ativo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredientes', 'Ativo')
    # ### end Alembic commands ###
