"""adição de unidade medida nos itens de estoque para melhor controle de quantidade junto aos itens_ingredientes

Revision ID: edca2c0449bd
Revises: 52c692def578
Create Date: 2026-06-24 23:28:45.027812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edca2c0449bd'
down_revision: Union[str, Sequence[str], None] = '52c692def578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoqueItens', sa.Column('UnidadeMedida', sa.String(length=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estoqueItens', 'UnidadeMedida')
    # ### end Alembic commands ###
