"""fix na filial

Revision ID: f4b86233bd92
Revises: 39e30161fac2
Create Date: 2026-06-15 23:47:05.114117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f4b86233bd92'
down_revision: Union[str, Sequence[str], None] = '39e30161fac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filiais', 'ContaBanco',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filiais', 'ContaBanco',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
