"""Adição de identificador de log

Revision ID: fcc0b579fdb6
Revises: 4748b720e995
Create Date: 2026-06-22 17:00:31.363365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc0b579fdb6'
down_revision: Union[str, Sequence[str], None] = '4748b720e995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'Nascimento',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'Nascimento',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
