"""id_modificado dos logs como string por precisar identificar mais valores

Revision ID: fe39a3dff618
Revises: 59a294014e17
Create Date: 2026-06-23 12:24:44.750916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fe39a3dff618'
down_revision: Union[str, Sequence[str], None] = '59a294014e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'IdModificado',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'IdModificado',
               existing_type=sa.String(length=12),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
